name: Notify Telegram on New Issue

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
           -d text="<b>New issue in repository:</b> ${{ github.repository }}%0A<b>Title:</b> ${{ github.event.issue.title }}%0A<b>URL:</b> ${{ github.event.issue.html_url }}" \
           -d parse_mode="HTML"